---
title: "Análise do Saldo em Conta Corrente"
author: "Douglas Mangini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r libraries}
library(tidyverse)
library(lubridate)
```

```{r data}
df <- list.files(pattern = "*.csv") %>%
  map_df(~read_delim(.,
                   delim = ";", 
                   escape_double = FALSE, 
                   col_names = c("data","ocasião","valor","saldo"), 
                   col_types = cols(
                            data = col_date(format = "%d/%m/%Y")), 
                   locale = locale(
                            time_format = "%d/%m/%y", 
                            decimal_mark = ",", 
                            grouping_mark = ".", 
                            encoding = "ISO-8859-1"),
                   trim_ws = TRUE, 
                   skip = 8)) %>%
  separate(ocasião, into = c("trans","detalhe"), sep = "-") %>%
  mutate(valor = parse_number(str_remove(valor,pattern = "-"),
                              locale = locale(grouping_mark = ".")),
         dif = (saldo - lag(saldo)),
         trans = str_to_title(trans)) %>%
  filter(valor != 0, !is.na(valor) == TRUE)
```

```{r params for plot}
last_date <- str_c("Última transação: ",last(df$data))
y_label <- seq(2000,5000, by =100)
saldo_atual <- str_c("R$",format(last(df$saldo), big.mark = ".", decimal.mark = ","))
maior_valor <- str_c("R$ ",max(df$valor))
maior_trans <- str_c(filter(df, valor == max(valor))[[2]] , filter(df, valor == max(valor))[[3]])

```

### Período

Este relatório cobre o período entre **`r min(df$data)`** e **`r max(df$data)`**. 


### Saldo Atual
O saldo atual é de `r saldo_atual`. 

### Maior Transação
A maior transação do período foi `r maior_trans`, no valor de `r  maior_valor`.

 

```{r plot_saldo}

ggplot(df, aes(data,saldo))+
  geom_line(size = 1)+
   labs(
     title = "Saldo em conta corrente no banco inter",
     subtitle = last_date)+
    scale_x_date(date_breaks = "5 days", date_labels = "%d/%b")+
    scale_y_continuous(breaks =y_label, labels = str_c("R$",y_label))+
  theme_minimal()
```

